# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MmInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('credit_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_category', models.IntegerField(blank=True, choices=[(1, b'A'), (2, b'B'), (3, b'C'), (4, b'D')], null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('credits_available', models.IntegerField(default=0)),
                ('credits_spent', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_successful_posts', models.IntegerField(default=0)),
                ('money_invested', models.ManyToManyField(blank=True, null=True, through='auth_app.MmInvestment', to='auth_app.Person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.CharField(max_length=10)),
                ('amount_received', models.CharField(max_length=10)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mminvestment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to='auth_app.Person'),
        ),
        migrations.AddField(
            model_name='mminvestment',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker', to='auth_app.Person'),
        ),
    ]
